# Practice for Join Statements with SQL

Import the necessary packages and connect to the database 'data.sqlite'.

In [37]:
# Run without change

# Libraries and database

import sqlite3
import pandas as pd

conn = sqlite3.connect('data.sqlite')

pd.read_sql(""" select * from employees """, conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

1. Select the names (frist and last) of all employees in Boston

In [38]:
# Your code here

pd.read_sql(""" SELECT firstName, lastName FROM employees JOIN offices USING(officeCode) WHERE city = 'Boston';""", conn)

  firstName   lastName
0     Julie   Firrelli
1     Steve  Patterson

2. Are there any offices that have zero employees?

In [39]:
# Your code here
pd.read_sql(""" select o.officeCode, o.city from offices o LEFT JOIN  employees e using(officeCode) group by officeCode having count(e.employeeNumber) = 0;""", conn)

   officeCode    city
0          27  Boston

3. How many customers are there per office?

In [40]:
# Your code here
pd.read_sql(""" select c.officeCode, count(e.salesRepEmployeeNumber), o.city from offices o join employees c using(officeCode) join customers e on c.employeeNumber = e.salesRepEmployeeNumber group by officeCode ; """, conn)

   officeCode  count(e.salesRepEmployeeNumber)           city
0           1                               12  San Francisco
1           2                               12         Boston
2           3                               15            NYC
3           4                               29          Paris
4           5                                5          Tokyo
5           6                               10         Sydney
6           7                               17         London

4. Display the names of every individual product that each employee has sold as a dataframe.

In [41]:
# Your code here
pd.read_sql(""" 
            
           select firstName, lastName, productName from employees e join customers c on e.employeeNumber = c.salesRepEmployeeNumber
           join orders using(customerNumber)
           join orderDetails using(orderNumber)
           join products using(productCode) 
            
            
            
            ; """, conn)

     firstName  lastName                                  productName
0       Leslie  Jennings                               1958 Setra Bus
1       Leslie  Jennings                       1940 Ford Pickup Truck
2       Leslie  Jennings                      1939 Cadillac Limousine
3       Leslie  Jennings  1996 Peterbilt 379 Stake Bed with Outrigger
4       Leslie  Jennings                            1968 Ford Mustang
...        ...       ...                                          ...
2991    Martin    Gerard                  1954 Greyhound Scenicruiser
2992    Martin    Gerard       1950's Chicago Surface Lines Streetcar
2993    Martin    Gerard             Diamond T620 Semi-Skirted Tanker
2994    Martin    Gerard                           1911 Ford Town Car
2995    Martin    Gerard             1936 Mercedes Benz 500k Roadster

[2996 rows x 3 columns]

5. Display the number of products each employee has sold
- Alphabetize the results by employee last name.
- Use the quantityOrdered column from orderDetails.
- Think about how to group the data when some employees might have the same first or last name.

In [42]:
# Your code here

pd.read_sql(""" 
            
           select firstName, lastName, SUM(quantityOrdered) as total_products_sold from employees e join customers c on e.employeeNumber = c.salesRepEmployeeNumber
           join orders using(customerNumber)
           join orderDetails using(orderNumber)
           group by firstName, lastName
           order by lastName            
            
            
            ; """, conn)

   firstName   lastName  total_products_sold
0       Loui     Bondur                 6186
1      Larry       Bott                 8205
2     Pamela   Castillo                 9290
3      Julie   Firrelli                 4227
4       Andy     Fixter                 6246
5     Martin     Gerard                 4180
6     Gerard  Hernandez                14231
7     Leslie   Jennings                11854
8      Barry      Jones                 7486
9      Peter      Marsh                 6632
10      Mami      Nishi                 4923
11     Steve  Patterson                 5561
12    Leslie   Thompson                 4056
13  Foon Yue      Tseng                 5016
14    George     Vanauf                 7423

6.  Display the names of employees who have sold more than 200 different products.

In [43]:
# Your codde here
pd.read_sql(""" 
            
           select firstName, lastName, COUNT(productCode) as different_products_sold from employees e join customers c on e.employeeNumber = c.salesRepEmployeeNumber
           join orders using(customerNumber)
           join orderDetails using(orderNumber)
           group by firstName, lastName
           having different_products_sold > 200
           order by lastName      
            
            
            ; """, conn)

  firstName   lastName  different_products_sold
0     Larry       Bott                      236
1    Pamela   Castillo                      272
2    Gerard  Hernandez                      396
3    Leslie   Jennings                      331
4     Barry      Jones                      220
5    George     Vanauf                      211

In [44]:
conn.close()